# Generated by Django 2.0 on 2018-01-02 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=None, max_length=250, null=True)),
                ('last_name', models.CharField(blank=None, max_length=250, null=True)),
                ('starts', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chef',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Dishes',
                'ordering': ['id'],
                'db_table': 'dish',
                'verbose_name': 'Dish',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=None, max_length=250, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('state', models.CharField(default='Draft', max_length=20)),
                ('uuid', models.UUIDField(default='bbe65bae283d415fb5704410db2c1b53')),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chef_menus', to='manager.Chef')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_menus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Menu')),
            ],
            options={
                'verbose_name_plural': 'Menu Options',
                'db_table': 'menu_option',
                'verbose_name': 'Menu Option',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=250, null=True)),
                ('code', models.CharField(blank=None, max_length=15, null=True)),
                ('chef_recommendations', models.TextField(blank=True, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'option',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OptionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('starts', models.PositiveIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='option_comments', to='manager.Option')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Option Comments',
                'ordering': ['-created_at'],
                'db_table': 'option_comment',
                'verbose_name': 'Option Comment',
            },
        ),
        migrations.CreateModel(
            name='OptionDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dishes', to='manager.Dish')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='manager.Option')),
            ],
            options={
                'db_table': 'option_dish',
            },
        ),
        migrations.CreateModel(
            name='SequenceOfMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sequences of meals',
                'db_table': 'sequences_of_meal',
            },
        ),
        migrations.AddField(
            model_name='menuoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Option'),
        ),
        migrations.AddField(
            model_name='dish',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Group'),
        ),
        migrations.AddField(
            model_name='dish',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.SequenceOfMeal'),
        ),
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_dishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
